
import pandas as pd


df = pd.read_csv(r"C:\Users\bilal\Desktop\BigDataOrdersDashboard\Büyük Veri Analitiği Güncel Kurs Dosyaları\eu_products_18000.csv")

print(df.head())
print("************")
print(df.tail())
print("************")
print(df.info())
print("************")
print(df.describe())
print("************")
print(df.columns)
print("************")
print(df.dtypes)
print("************")
print(df.shape)
print("************")
print(df.index)
print("************")
print(df.values)
print("************")
print(df.sample(5))
print("--------------------------------------------------------------------------------------------------------------------------------------------------------")

print(df.nunique())
print("************")
print(df.isnull().sum())
print("************")
print(df.duplicated().sum())
print("************")
print(df.sort_values(by='UnitPrice', ascending=False).head())
print("************")
print(df.groupby('CategoryId')['UnitPrice'].mean())
print("************")
print(df['CategoryId'].value_counts())
print("************")
#print(df.corr())
print("--------------------------------------------------------------------------------------------------------------------------------------------------------")
print(df['ProductName'].str.upper().head())
print("************")
print(df['ProductName'].str.contains('Çikolata').head())
print("************")
print(df['ProductName'].str.len().head())
print("************")
print(df['ProductName'].str.replace('Çikolata', 'Choco').head())
print("************")
print(df['ProductName'].str.split().head())
print("************")
print(df['ProductName'].str.slice(0, 10).head())
print("************")
#print(df['ProductName'].str.cat(sep=', ').head())
print("************")
print(df['ProductName'].str.get_dummies(sep=' ').head())
print("************")
print(df['ProductName'].str.extract(r'([A-Za-z]+)').head())
print("************")
print(df['ProductName'].str.count('a').head())
print("************")
print(df['ProductName'].str.startswith('A').head())
print("************")
print(df['ProductName'].str.endswith('e').head())
print("************")
print(df['ProductName'].str.find('e').head())
print("************")
print("************")
print(df['ProductName'].str.zfill(20).head())
print("************")
print(df['ProductName'].str.center(30, '*').head())
print("************")
print(df['ProductName'].str.ljust(30, '-').head())
print("************")
print(df['ProductName'].str.rjust(30, '+').head())
print("************")
print(df['ProductName'].str.strip().head())
print("************")
print(df['ProductName'].str.rstrip().head())
print("************")
print(df['ProductName'].str.lstrip().head())
print("************")
print(df['ProductName'].str.repeat(2).head())
print("************")
print(df['ProductName'].str.swapcase().head())
print("************")
print(df['ProductName'].str.title().head())
print("************")
print(df['ProductName'].str.normalize('NFKD').head())
print("************")
print(df['ProductName'].str.encode('utf-8').head())
print("************")
print(df['ProductName'].str.decode('utf-8', 'ignore').head())
print("************")
print(df['ProductName'].str.translate(str.maketrans({'a': '1',
                                                    'e': '2',
                                                    'i': '3',
                                                    'o': '4',
                                                    'u': '5'})).head())
print("--------------------------------------------------------------------------------------------------------------------------------------------------------")
print(df['ProductName'].str.normalize('NFC').head())
print("************")
print(df['ProductName'].str.normalize('NFD').head())
print("************")
print(df['ProductName'].str.normalize('NFKC').head())
print("************")
print("Pandas işlemleri başarıyla tamamlandı.")
print("--------------------------------------------------------------------------------------------------------------------------------------------------------")

